### This notebook is to perform permanova tests on unweighted UniFrac (qiime1 environment).

#### 1. Categorical Covariates (Permanova Test)

In [ ]:
# Race (p-value = 0.001 ***)
compare_categories.py -i ../Qiime_updated/core-metrics-results/unweighted_unifrac_distance/distance-matrix.tsv \
-m ../data/mros_mapping_alpha.txt \
-c GIERACE \
-o ../beta-uw-results/unweighted-unifrac-GIERACE --method permanova

In [ ]:
# Site (p-value = 0.001 ***)
compare_categories.py -i ../Qiime_updated/core-metrics-results/unweighted_unifrac_distance/distance-matrix.tsv \
-m ../data/mros_mapping_alpha.txt \
-c SITE \
-o ../beta-uw-results/unweighted-unifrac-SITE --method permanova 

In [ ]:
# TUDRAMT (0.023)
compare_categories.py -i ../Qiime_updated/core-metrics-results/unweighted_unifrac_distance/distance-matrix.tsv \
-m ../data/mros_mapping_alpha.txt \
-c TUDRAMT \
-o ../beta-uw-results/unweighted-unifrac-TUDRAMT --method permanova 

In [ ]:
# TURSMOKE (0.07)
compare_categories.py -i ../Qiime_updated/core-metrics-results/unweighted_unifrac_distance/distance-matrix.tsv \
-m ../data/mros_mapping_alpha.txt \
-c TURSMOKE \
-o ../beta-uw-results/unweighted-unifrac-TURSMOKE --method permanova 

In [ ]:
# Antidepressant Use (p-value = 0.001 ***)
compare_categories.py -i ../Qiime_updated/core-metrics-results/unweighted_unifrac_distance/distance-matrix.tsv \
-m ../data/mros_mapping_alpha.txt \
-c M1ADEPR \
-o ../beta-uw-results/unweighted-unifrac-M1ADEPR --method permanova

In [ ]:
# M1VITMND (0.709)
compare_categories.py -i ../Qiime_updated/core-metrics-results/unweighted_unifrac_distance/distance-matrix.tsv \
-m ../data/mros_mapping_alpha.txt \
-c M1VITMND \
-o ../beta-uw-results/unweighted-unifrac-M1VITMND --method permanova

In [ ]:
# Antibiotic Use (p-value = 0.001 ***)
compare_categories.py -i ../Qiime_updated/core-metrics-results/unweighted_unifrac_distance/distance-matrix.tsv \
-m ../data/mros_mapping_alpha.txt \
-c M1ANTIB \
-o ../beta-uw-results/unweighted-unifrac-M1ANTIB --method permanova

In [ ]:
# M1PROBI (p-value = 0.575)
compare_categories.py -i ../Qiime_updated/core-metrics-results/unweighted_unifrac_distance/distance-matrix.tsv \
-m ../data/mros_mapping_alpha.txt \
-c M1PROBI \
-o ../beta-uw-results/unweighted-unifrac-M1PROBI --method permanova 

In [ ]:
# OHSEAS (p-value = 0.152)
compare_categories.py -i ../Qiime_updated/core-metrics-results/unweighted_unifrac_distance/distance-matrix.tsv \
-m ../data/mros_mapping_alpha.txt \
-c OHSEAS \
-o ../beta-uw-results/unweighted-unifrac-OHSEAS --method permanova 

In [ ]:
# QLCOMP (p-value = 0.043)
compare_categories.py -i ../Qiime_updated/core-metrics-results/unweighted_unifrac_distance/distance-matrix.tsv \
-m ../data/mros_mapping_alpha.txt \
-c QLCOMP \
-o ../beta-uw-results/unweighted-unifrac-QLCOMP --method permanova 

In [ ]:
# VDstatus (p-value = 0.796)
compare_categories.py -i ../Qiime_updated/core-metrics-results/unweighted_unifrac_distance/distance-matrix.tsv \
-m ../data/mros_mapping_alpha.txt \
-c VDstatus \
-o ../beta-uw-results/unweighted-unifrac-VDstatus --method permanova

In [ ]:
# Statin Use (p-value = 0.01 **)
compare_categories.py -i ../Qiime_updated/core-metrics-results/unweighted_unifrac_distance/distance-matrix.tsv \
-m ../data/mros_mapping_alpha.txt \
-c M1STATIN \
-o ../beta-uw-results/unweighted-unifrac-M1STATIN --method permanova

In [ ]:
# Antihistamine (0.407)
compare_categories.py -i ../Qiime_updated/core-metrics-results/unweighted_unifrac_distance/distance-matrix.tsv \
-m ../data/mros_mapping_alpha.txt \
-c Antihistamine \
-o ../beta-uw-results/unweighted-unifrac-Antihistamine --method permanova

In [ ]:
# Laxative (p-value = 0.076)
compare_categories.py -i ../Qiime_updated/core-metrics-results/unweighted_unifrac_distance/distance-matrix.tsv \
-m ../data/mros_mapping_alpha.txt \
-c Laxative \
-o ../beta-uw-results/unweighted-unifrac-Laxative --method permanova

In [1]:
from statsmodels.sandbox.stats.multicomp import multipletests
multipletests([0.001,0.001, 0.023, 0.07, 0.001, 0.709, 0.001, 0.575, 
               0.152, 0.043, 0.796, 0.01, 0.407, 0.076],
               alpha=0.05, method='fdr_bh') 

(array([ True,  True, False, False,  True, False,  True, False, False,
        False, False,  True, False, False]),
 array([0.0035    , 0.0035    , 0.05366667, 0.11822222, 0.0035    ,
        0.76353846, 0.0035    , 0.67083333, 0.2128    , 0.086     ,
        0.796     , 0.028     , 0.518     , 0.11822222]),
 0.0036571031913835705,
 0.0035714285714285718)

#### 2. Continous Covariates (Adonis Test)

In [ ]:
# Age (p-value = 0.03 *)
compare_categories.py -i ../Qiime_updated/core-metrics-results/unweighted_unifrac_distance/distance-matrix.tsv \
-m ../data/mros_mapping_alpha.txt \
-c Age \
-o ../beta-uw-results/unweighted-unifrac-Age --method adonis

In [ ]:
# BMI (p-value = 0.009 **)
compare_categories.py -i ../Qiime_updated/core-metrics-results/unweighted_unifrac_distance/distance-matrix.tsv \
-m ../data/mros_mapping_alpha.txt \
-c BMI \
-o ../beta-uw-results/unweighted-unifrac-BMI --method adonis

In [ ]:
# Pascore (p-value = 0.014 *)
compare_categories.py -i ../Qiime_updated/core-metrics-results/unweighted_unifrac_distance/distance-matrix.tsv \
-m ../data/mros_mapping_alpha.txt \
-c PASCORE \
-o ../beta-uw-results/unweighted-unifrac-PASCORE --method adonis

#### filter metadata based on vitD measurements

In [20]:
import numpy as np
import pandas as pd

In [21]:
mf = pd.read_csv('../data/mros_mapping_alpha.txt', sep='\t', index_col='#SampleID')

In [22]:
mf.head()

BarcodeSequence  LinkerPrimerSequence  \
#SampleID                                         
BI0023       TCTGGTGACATT  GGACTACHVGGGTWTCTAAT   
BI0056       CAAGCATGCCTA  GGACTACHVGGGTWTCTAAT   
BI0131       CTATTTGCGACA  GGACTACHVGGGTWTCTAAT   
BI0153       ATCGGCGTTACA  GGACTACHVGGGTWTCTAAT   
BI0215       CCTCTCGTGATC  GGACTACHVGGGTWTCTAAT   

                               Experiment_Design_Description  \
#SampleID                                                      
BI0023     16S stool samples sequenced for MrOS Vitamin D...   
BI0056     16S stool samples sequenced for MrOS Vitamin D...   
BI0131     16S stool samples sequenced for MrOS Vitamin D...   
BI0153     16S stool samples sequenced for MrOS Vitamin D...   
BI0215     16S stool samples sequenced for MrOS Vitamin D...   

          Library_Construction_Protocol Linker  Platform Center_Name  \
#SampleID                                                              
BI0023                      16S rRNA v4     GT  Illumina          BI   
BI0056                      16S rRNA v4     GT  Illumina          BI   
BI0131                      16S rRNA v4     GT  Illumina          BI   
BI0153                      16S rRNA v4     GT  Illumina          BI   
BI0215                      16S rRNA v4     GT  Illumina          BI   

          Center_Project Instrument_Model          Title    ...    M1STATIN  \
#SampleID                                                   ...               
BI0023              MrOS   Illumina MiSeq  MrOS_VitaminD    ...       0: No   
BI0056              MrOS   Illumina MiSeq  MrOS_VitaminD    ...       0: No   
BI0131              MrOS   Illumina MiSeq  MrOS_VitaminD    ...      1: Yes   
BI0153              MrOS   Illumina MiSeq  MrOS_VitaminD    ...      1: Yes   
BI0215              MrOS   Illumina MiSeq  MrOS_VitaminD    ...       0: No   

          Antihistamine Laxative  MIDATA Rstarch_total Rstarches_c   alpha_pd  \
#SampleID                                                                       
BI0023             0:No     0:No  1: Yes      3.066569         0.0  27.771167   
BI0056             0:No     0:No  1: Yes      3.038136         0.0  17.932659   
BI0131             0:No     0:No  1: Yes      2.840599         0.0  21.453663   
BI0153             0:No     0:No  1: Yes      4.106798         0.0  18.469675   
BI0215             0:No     0:No  1: Yes      0.971114         0.0  20.049827   

          observed_otus   shannon  pielou_e  
#SampleID                                    
BI0023              302  5.727116  0.695173  
BI0056              173  3.888281  0.522996  
BI0131              223  4.050730  0.519264  
BI0153              223  4.894253  0.627396  
BI0215              222  5.295055  0.679340  

[5 rows x 77 columns]

In [23]:
mf.shape

(599, 77)

In [24]:
mf = mf.loc[:, ('OHVD3', 'OHV1D3', 'OHV24D3', 'ratio_activation', 'ratio_catabolism')]

In [25]:
mf.head()

OHVD3  OHV1D3  OHV24D3  ratio_activation  ratio_catabolism
#SampleID                                                            
BI0023      25.8  0.0393     1.77          0.001523          0.068605
BI0056      39.2  0.0619     3.91          0.001579          0.099745
BI0131      23.1  0.0521     1.49          0.002255          0.064502
BI0153      27.3  0.0431     2.14          0.001579          0.078388
BI0215      33.0  0.0502     3.62          0.001521          0.109697

In [26]:
mf.dropna(axis=0, how='any', inplace=True)

In [27]:
mf.to_csv('../data/mf.vitD.txt', sep='\t', index_label='#SampleID')

In [19]:
# filter the distance matrix based on filtered metadata file
filter_distance_matrix.py -i ../Qiime_updated/core-metrics-results/unweighted_unifrac_distance/distance-matrix.tsv  \
-o ../data/unweighted.dm.filtered.txt \
--sample_id_fp ../data/mf.vitd.ids.txt

In [ ]:
# 1, 25 (p-value = 0.001 ***)
compare_categories.py -i ../data/unweighted.dm.filtered.txt \
-m ../data/mf.vitD.txt \
-c OHV1D3 \
-o ../beta-uw-results/unweighted-unifrac-OHV1D3 --method adonis

In [ ]:
# 25 (p-value = 0.085)
compare_categories.py -i ../data/unweighted.dm.filtered.txt \
-m ../data/mf.vitD.txt \
-c OHVD3 \
-o ../beta-uw-results/unweighted-unifrac-OHVD3 --method adonis

In [ ]:
# 24 (p-value = 0.002 **)
compare_categories.py -i ../data/unweighted.dm.filtered.txt \
-m ../data/mf.vitD.txt \
-c OHV24D3 \
-o ../beta-uw-results/unweighted-unifrac-OHV24D3 --method adonis

In [ ]:
# ratio_act (p-value = 0.001 ***)
compare_categories.py -i ../data/unweighted.dm.filtered.txt \
-m ../data/mf.vitD.txt \
-c ratio_activation \
-o ../beta-uw-results/unweighted-unifrac-ratio_activation --method adonis

In [ ]:
# ratio_cat (p-value = 0.001 ***)
compare_categories.py -i ../data/unweighted.dm.filtered.txt \
-m ../data/mf.vitD.txt \
-c ratio_catabolism \
-o ../beta-uw-results/unweighted-unifrac-ratio_catabolism --method adonis

In [28]:
from statsmodels.sandbox.stats.multicomp import multipletests
multipletests([0.03, 0.009, 0.014, 0.001, 0.085, 0.002, 0.001, 0.001], alpha=0.05, method='fdr_bh') 

(array([ True,  True,  True,  True, False,  True,  True,  True]),
 array([0.03428571, 0.0144    , 0.01866667, 0.00266667, 0.085     ,
        0.004     , 0.00266667, 0.00266667]),
 0.006391150954545011,
 0.00625)